#! /bin/sh

#### Auto Start

pgrep -x sxhkd > /dev/null || sxhkd &

 # Dual Monitors
xrandr --output DVI-D-0 --off --output HDMI-0 --mode 1920x1080 --pos 1920x0 --rotate normal --output DP-0 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1 --off --output DP-2 --off --output DP-3 --off --output DP-4 --off --output DP-5 --off &

 # Picom
picom --config ~/.config/picom/picom.conf &

 # Wallpaper
feh --bg-scale /mnt/Media/wallpapers/tokyonight.jpg &

 # redshift screen
redshift -O 4500 -r -P &
 
 # PolyBar
$HOME/.config/polybar/launch.sh  &

 # Japanese Input
fcitx -d &

wmname LG3D &


#############################

#### Work Space


bspc monitor DP-0 -d    1 2 3 4 5 6 7 8 9
bspc monitor HDMI-0 -d  1 2 3 4 5 6 7 8 9

bspc config border_width         5
bspc config focused_border_color "#33467c"
bspc config window_gap          10

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a discord desktop='^3' 
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a android-studio state=floating border=off follow=on
